sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

after_success:
  - docker login -u erikrotaru -p rot69aru

# CHARGER-NETWORK-CONFIG SERVICE
  - docker build -t charger-network-config ./charger-network-config
  - docker tag charger-network-config erikrotaru/charger-network-config
  - docker push erikrotaru/charger-network-config
