version: '2'
services:
    charger-network-config:
        container_name: charger-network-config
        build:
            context: ./charger-network-config
            dockerfile: Dockerfile
        image: charger-network-config
        expose:
            - 8101
        ports:
            - "8101:8101"
        networks:
            - spring-cloud-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        logging:
            driver: json-file
    charger-network-discovery:
        container_name: charger-network-discovery
        build:
            context: ./charger-network-discovery
            dockerfile: Dockerfile
        image: charger-network-discovery
        entrypoint: /opt/bin/config-discovery-entrypoint.sh
        expose:
            - 8761
        ports:
            - "8761:8761"
        networks:
            - spring-cloud-network
        links:
            - charger-network-config:charger-network-config
        depends_on:
            - charger-network-config
        logging:
            driver: json-file
    charger-network-gateway:
        container_name: charger-network-gateway
        build:
            context: ./charger-network-gateway
            dockerfile: Dockerfile
        image: charger-network-gateway
        entrypoint: /opt/bin/config-gateway-entrypoint.sh
        expose:
            - 8100
        ports:
            - "8100:8100"
        networks:
            - spring-cloud-network
        links:
            - charger-network-discovery:charger-network-discovery
        depends_on:
            - charger-network-config
            - charger-network-discovery
        logging:
            driver: json-file
    charger-network-manager:
        container_name: charger-network-manager
        build:
            context: ./charger-network-manager
            dockerfile: Dockerfile
        image: charger-network-manager
        entrypoint: /opt/bin/charger-network-manager-entrypoint.sh
        expose:
            - 8103
        ports:
            - "8103:8103"
        networks:
            - spring-cloud-network
            - charger-client-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        links:
            - charger-network-config:charger-network-config
            - charger-network-discovery:charger-network-discovery
        depends_on:
            - charger-network-gateway
        logging:
            driver: json-file
    charger-account-manager:
        container_name: charger-account-manager
        build:
            context: ./charger-account-manager
            dockerfile: Dockerfile
        image: charger-account-manager
        entrypoint: /opt/bin/charger-account-manager-entrypoint.sh
        expose:
            - 8104
        ports:
            - "8104:8104"
        networks:
            - spring-cloud-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        links:
            - charger-network-config:charger-network-config
            - charger-network-discovery:charger-network-discovery
        depends_on:
            - charger-network-gateway
        logging:
            driver: json-file
    charger-client-simulator:
        container_name: charger-client-simulator
        build:
            context: ./charger-client-simulator
            dockerfile: Dockerfile
        image: charger-client-simulator
        entrypoint: /opt/bin/charger-client-simulator-entrypoint.sh
        expose:
            - 8105
        ports:
            - "8105:8105"
        networks:
            - spring-cloud-network
            - charger-client-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        links:
            - charger-network-config:charger-network-config
            - charger-network-discovery:charger-network-discovery
        depends_on:
            - charger-network-gateway
        logging:
            driver: json-file
networks:
    spring-cloud-network:
        driver: bridge
    charger-client-network:
        driver: bridge
volumes:
    spring-cloud-config-repo:
        external: true
