version: '2'
services:
    charger-network-config:
        container_name: charger-network-config
        build:
            context: ./charger-network-config
            dockerfile: Dockerfile
        image: charger-network-config:latest
        expose:
            - 8101
        networks:
            - spring-cloud-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        logging:
            driver: json-file
    charger-network-discovery:
        container_name: charger-network-discovery
        build:
            context: ./charger-network-discovery
            dockerfile: Dockerfile
        image: charger-network-discovery:latest
        entrypoint: /opt/bin/config-client-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://charger-network-config:8101"}}}}'
        expose:
            - 8102
        ports:
            - 8102:8102
        networks:
            - spring-cloud-network
        links:
            - charger-network-config:charger-network-config
        depends_on:
            - charger-network-config
        logging:
            driver: json-file
networks:
    spring-cloud-network:
        driver: bridge
volumes:
    spring-cloud-config-repo:
        external: true
