version: '2'
services:
    charger-network-config:
        build:
            context: ./charger-network-config
            dockerfile: Dockerfile
        image: charger-network-config:latest
        expose:
            - 8101
        ports:
            - "8101:8101"
        networks:
            - spring-cloud-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        logging:
            driver: json-file
    charger-network-discovery:
        build:
            context: ./charger-network-discovery
            dockerfile: Dockerfile
        image: charger-network-discovery:latest
        entrypoint: /opt/bin/config-discovery-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://charger-network-config:8101"}}}}'
        expose:
            - 8102
        ports:
            - "8102:8102"
        networks:
            - spring-cloud-network
        links:
            - charger-network-config:charger-network-config
        depends_on:
            - charger-network-config
        logging:
            driver: json-file
    charger-network-gateway:
        build:
            context: ./charger-network-gateway
            dockerfile: Dockerfile
        image: charger-network-gateway:latest
        entrypoint: /opt/bin/config-gateway-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://charger-network-config:8101"}}}}'
        expose:
            - 8100
        ports:
            - "8100:8100"
        networks:
            - spring-cloud-network
        links:
            - charger-network-discovery:charger-network-discovery
        depends_on:
            - charger-network-config
            - charger-network-discovery
        logging:
            driver: json-file
    charger-network-manager:
        build:
            context: ./charger-network-manager
            dockerfile: Dockerfile
        image: charger-network-manager:latest
        entrypoint: /opt/bin/charger-network-manager-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://charger-network-config:8101"}}}}'
        expose:
            - 8103
        ports:
            - "8103:8103"
        networks:
            - spring-cloud-network
        links:
            - charger-network-discovery:charger-network-discovery
        depends_on:
            - charger-network-config
            - charger-network-discovery
            - charger-network-gateway
        logging:
            driver: json-file
networks:
    spring-cloud-network:
        driver: bridge
volumes:
    spring-cloud-config-repo:
        external: true
