version: '3'
services:
    charger-network-config:
        container_name: charger-network-config
        build:
            context: ./charger-network-config
            dockerfile: Dockerfile
        image: charger-network-config
        expose:
            - 8101
        ports:
            - "8101:8101"
        networks:
            - spring-cloud-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        logging:
            driver: json-file
    charger-network-discovery:
        container_name: charger-network-discovery
        build:
            context: ./charger-network-discovery
            dockerfile: Dockerfile
        image: charger-network-discovery
        entrypoint: /opt/bin/config-discovery-entrypoint.sh
        expose:
            - 8761
        ports:
            - "8761:8761"
        networks:
            - spring-cloud-network
        depends_on:
            - charger-network-config
        logging:
            driver: json-file
    charger-network-gateway:
        container_name: charger-network-gateway
        build:
            context: ./charger-network-gateway
            dockerfile: Dockerfile
        image: charger-network-gateway
        entrypoint: /opt/bin/config-gateway-entrypoint.sh
        expose:
            - 8100
        ports:
            - "8100:8100"
        networks:
            - spring-cloud-network
        depends_on:
            - charger-network-config
            - charger-network-discovery
        logging:
            driver: json-file
    charger-network-manager:
        container_name: charger-network-manager
        build:
            context: ./charger-network-manager
            dockerfile: Dockerfile
        image: charger-network-manager
        entrypoint: /opt/bin/charger-network-manager-entrypoint.sh
        expose:
            - 8103
        ports:
            - "8103:8103"
        networks:
            - spring-cloud-network
            - charger-client-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        depends_on:
            - charger-network-gateway
        logging:
            driver: json-file
    charger-account-manager:
        container_name: charger-account-manager
        build:
            context: ./charger-account-manager
            dockerfile: Dockerfile
        image: charger-account-manager
        entrypoint: /opt/bin/charger-account-manager-entrypoint.sh
        environment:
            - MONGODB_URI=mongodb://charger-accounts-mongodb:27017/accounts
        expose:
            - 8104
        ports:
            - "8104:8104"
        networks:
            - spring-cloud-network
            - charger-accounts-mongodb-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        depends_on:
            - charger-network-gateway
        logging:
            driver: json-file
    charger-client-simulator:
        container_name: charger-client-simulator
        build:
            context: ./charger-client-simulator
            dockerfile: Dockerfile
        image: charger-client-simulator
        entrypoint: /opt/bin/charger-client-simulator-entrypoint.sh
        expose:
            - 8105
        ports:
            - "8105:8105"
        networks:
            - spring-cloud-network
            - charger-client-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        depends_on:
            - charger-network-gateway
        logging:
            driver: json-file
    charger-accounts-mongodb:
        container_name: charger-accounts-mongodb
        build:
            context: ./mongodb
            dockerfile: Dockerfile
        image: charger-accounts-mongodb
        networks:
            - charger-accounts-mongodb-network
        volumes: 
            - charger-accounts:/data/db
        expose:
            - 27017
        ports:
            - 12345:27017
    kafka:
        container_name: kafka
        build:
            context: ./kafka
            dockerfile: Dockerfile
        image: kafka
        networks:
            - kafka
        expose:
            - 9092
        ports:
            - 9092:9092
        depends_on:
            - zookeeper
    zookeeper:
        container_name: zookeeper
        build:
            context: ./zookeeper
            dockerfile: Dockerfile
        image: zookeeper
        networks:
            - kafka
        expose:
            - 2181
        ports:
            - 2181:2181
networks:
    spring-cloud-network:
        driver: bridge
    charger-client-network:
        driver: bridge
    charger-accounts-mongodb-network:
        driver: bridge
    kafka:
        driver: bridge
volumes:
    spring-cloud-config-repo:
        external: true
    charger-accounts:
        external: true
